import { Container, Header } from '@/shared/components';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next Pizza | Панель',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Header hasSearch={false} hasCart={false} className="border-b-gray-200" />
        {children}
      </Container>
    </main>
  );
}
